server.port=8081
spring.application.name=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}
eureka.instance.prefer-ip-address=true


spring.datasource.url = jdbc:mysql://localhost:3306/userservicedb
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
